# Generated by Django 2.1.5 on 2020-07-31 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adopciones', '0004_auto_20200723_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=70)),
                ('telefono', models.IntegerField()),
                ('facebook', models.CharField(max_length=100)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Adopciones.Mascotas')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
