# Generated by Django 2.1.5 on 2020-07-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopciones', '0005_auto_20200731_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=70)),
                ('edad', models.IntegerField()),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='adoptante',
            name='mascota',
        ),
        migrations.DeleteModel(
            name='Adoptante',
        ),
    ]
